package editorGui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class GuiFrame extends JFrame {
    private JButton fileButton;
    private JButton editButton;
    private JToolBar menuBar;
    private JButton viewButton;
    private JButton searchButton;
    private JButton buildButton;
    private JTabbedPane editorTabs;
    private JEditorPane editorPane;
    private JScrollBar scrollBar1;
    private JScrollBar scrollBar2;
    private JPanel editorPanel;
    public JPanel mainPanel;

    public GuiFrame(String title) {
        super(title);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.pack();
        this.setVisible(true);
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("Code editorial");
//        frame.setContentPane(new GuiFrame().pa);
    }




    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        menuBar = new JToolBar();
        mainPanel.add(menuBar, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        fileButton = new JButton();
        fileButton.setText("File");
        menuBar.add(fileButton);
        final JToolBar.Separator toolBar$Separator1 = new JToolBar.Separator();
        menuBar.add(toolBar$Separator1);
        editButton = new JButton();
        editButton.setText("Edit");
        menuBar.add(editButton);
        final JToolBar.Separator toolBar$Separator2 = new JToolBar.Separator();
        menuBar.add(toolBar$Separator2);
        viewButton = new JButton();
        viewButton.setText("View");
        menuBar.add(viewButton);
        final JToolBar.Separator toolBar$Separator3 = new JToolBar.Separator();
        menuBar.add(toolBar$Separator3);
        searchButton = new JButton();
        searchButton.setText("Search");
        menuBar.add(searchButton);
        final JToolBar.Separator toolBar$Separator4 = new JToolBar.Separator();
        menuBar.add(toolBar$Separator4);
        buildButton = new JButton();
        buildButton.setText("Build");
        menuBar.add(buildButton);
        editorTabs = new JTabbedPane();
        mainPanel.add(editorTabs, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        editorPanel = new JPanel();
        editorPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        editorTabs.addTab("Untitled", editorPanel);
        editorPane = new JEditorPane();
        editorPanel.add(editorPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        scrollBar1 = new JScrollBar();
        editorPanel.add(scrollBar1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollBar2 = new JScrollBar();
        scrollBar2.setOrientation(0);
        editorPanel.add(scrollBar2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 1), null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
